return {
    {
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        branch = "main",
        build = ":TSUpdate",
        init = function()
            require("nvim-treesitter").install({
                "bash",
                "c",
                "cpp",
                "c_sharp",
                "diff",
                "go",
                "html",
                "javascript",
                "jsdoc",
                "json",
                "lua",
                "luadoc",
                "luap",
                "make",
                "markdown",
                "markdown_inline",
                "php",
                "printf",
                "python",
                "query",
                "regex",
                "hcl",
                "terraform",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
            })
        end,
    },
}
