alias vi="nvim"
alias vim="nvim"
alias view="nvim -R"
alias l="ls"
alias ls="ls -FG"
alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"
alias grep="grep --color"

# Config
alias kittyconf="vi ~/.config/kitty/kitty.conf"
alias tmuxconf="vi ~/.tmux.conf"
alias vimrc="vi ~/.vimrc"
alias dotfiles="vi ~/dotfiles"
